=== AntonioEstudillo/agenda-xml/agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT agenda (contancto*) >
<!ELEMENT contancto (nombre,apellido+,telefono,email?, direccion)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT direccion (calle, numero, cp)>

<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cp (#PCDATA)>


<!ATTLIST telefono pais CDATA #REQUIRED > 
<!ATTLIST nombre tipo (personal |  profesional) #REQUIRED>
<!ATTLIST telefono tipo (casa |  celular | trabajo) #REQUIRED>
<!ATTLIST email tipo (personal |  profesional) #REQUIRED>

=== AntonioEstudillo/agenda-xml/agaenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "./agenda.dtd" [
<!ENTITY saludo "Bienvenido a la agenda de contactos.">] >

<!--Contacto Personal con celular -->
<agenda>
    <contancto>
        <nombre tipo="personal">Antonio</nombre>
        <apellido>Estudillo</apellido>
        <apellido>Silva</apellido>
        <telefono tipo="celular" pais="México">+529212385389</telefono>
        <email tipo="personal">jesusestudillo123@gmail.com</email>        
        <direccion>
            <calle>José Guadalupe Posadas</calle>
            <numero>325</numero>
            <cp>96523</cp>
        </direccion>
    </contancto>

<!--Contacto Profesional con núm telefonico de trabajo -->
    <contancto>
        <nombre tipo="profesional">Alejandro</nombre>
        <apellido>Salvador</apellido>
        <apellido>Garduza</apellido>
        <telefono tipo="trabajo" pais="México">+529216247892</telefono>
        <email tipo="profesional">alejandrogar@uv.mx</email>        
        <direccion>
            <calle>Juan Escutia</calle>
            <numero>652</numero>
            <cp>96891</cp>
        </direccion>
    </contancto>
<!--Contacto Personal con celular -->
    <contancto>
        <nombre tipo="personal">Ulises</nombre>
        <apellido>Ramos</apellido>
        <apellido>Mexicano</apellido>
        <telefono pais="Estados Unidos" tipo="casa">+18007823412</telefono>
        <direccion>
            <calle>Mariano Escobedo</calle>
            <numero>523</numero>
            <cp>901</cp>
        </direccion>
    </contancto>

    <contancto>
        <nombre tipo="personal">Javier</nombre>
        <apellido>Chapa</apellido>
        <apellido>García</apellido>
        <telefono pais="México" tipo="celular">+529213457891</telefono>
        <email tipo="personal">javierchapa10@hotmail.com</email>
        <direccion>
            <calle>Paseo de las palmas</calle>
            <numero>871</numero>
            <cp>612</cp>
        </direccion>
    </contancto>

    <contancto>
        <nombre tipo="profesional">Jonathan</nombre>
        <apellido>H.Diaz</apellido>
        <telefono pais="México" tipo="casa">+51923412761</telefono>
        <email tipo="profesional">JonathanH10@outlook.com.mx</email>
        <direccion>
            <calle>Oriente 20</calle>
            <numero>023</numero>
            <cp>977</cp>
        </direccion>
    </contancto>
</agenda>
